### PR TITLE
Pass Craft Commerce Weight Unit setting to XML

### PR DESCRIPTION
**Pull request by jmauzyk**
Adds functionality to pass Craft Commerce weight unit setting to ShipStation and convert kilograms to grams when needed

### CODE REVIEW

**Comment by mkornatz** [comment]
Thanks for submitting a PR @jmauzyk. We'll be reviewing/testing soon!

**Comment by mkornatz** [comment]
Hey @jmauzyk, I was looking through this PR and figured it was a bit more complicated that it needed to be. Passing the `$units` through each of those mapping methods introduces a specific variable that only applies to a single Craft model when many others use that method. So, I opted for a simple approach in #39, which keeps it all contained to the item() method.

Thanks for your PR!

**Comment by mkornatz** [comment]
Closing in favor of #39

**Comment by jmauzyk** [comment]
Gotcha, makes sense. Thanks for adding this in!

**Pull request closed without merging**
